name: OLPT CI/CD

on:
  push:
    branches: ["main", "feat/**", "fix/**"]
  pull_request:

jobs:
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci
      - run: npm test

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci
      - run: npm run build
      - name: Upload FE artifact
        uses: actions/upload-artifact@v4
        with:
          name: fe-build
          path: frontend/build

  deploy-backend:
    name: Deploy Backend to EC2
    needs: [test-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy backend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "backend/*"
          target: "/home/${{ secrets.EC2_USER }}/apps/olpt/backend"
      - name: Install & Reload PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            cd ~/apps/olpt/backend
            npm ci
            pm2 startOrReload ecosystem.config.js --env production
            pm2 save
            pm2 status

  deploy-frontend:
    name: Deploy Frontend to EC2 (Nginx)
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Download FE artifact
        uses: actions/download-artifact@v4
        with:
          name: fe-build
          path: fe-build
      - name: Copy FE build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "fe-build/*"
          target: "/home/${{ secrets.EC2_USER }}/apps/olpt/frontend/build"
      - name: Move to Nginx web root
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf /var/www/olpt/*
            sudo mkdir -p /var/www/olpt
            sudo cp -r ~/apps/olpt/frontend/build/* /var/www/olpt/
            sudo systemctl reload nginx
